version: '{branch}.{build}'

environment:
  nodejs_version: 14

image: Visual Studio 2022

install:
- cmd: >-
    cd ./src/GregoryJenk.Mastermind.Web.Mvc

    npm install

before_build:
  nuget restore ../GregoryJenk.Mastermind.sln

build:
  project: ./src/GregoryJenk.Mastermind.sln
  verbosity: normal

test: on