version: 1.0.{build}
environment:
  nodejs_version: "6"
install:
- ps: Install-Product node $env:nodejs_version
- cmd: >-
    cd GregoryJenk.Mastermind\src\GregoryJenk.Mastermind.Web.Mvc

    # Seems like the global NPM install is causing an issue.
    #npm install -g npm

    npm install
before_build:
- cmd: >-
    dotnet --version

    dotnet restore

    dotnet build
build:
  verbosity: normal
test: off