version: 1.0.{build}
install:
- cmd: >-
    cd GregoryJenk.Mastermind\src\GregoryJenk.Mastermind.Web.Mvc

    npm install -g npm

    npm install
before_build:
- cmd: nuget restore GregoryJenk.Mastermind\GregoryJenk.Mastermind.sln
build:
  verbosity: normal