version: 1.0.{build}
install:
- cmd: >-
    cd

    cd GregoryJenk.Mastermind\src\GregoryJenk.Mastermind.Web.Mvc

    npm install -g npm

    npm install
before_build:
- cmd: >-
    dotnet --version

    cd

    nuget restore ..\..\GregoryJenk.Mastermind.sln
build:
  verbosity: normal