<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.0.0" />
    <PackageReference Include="Google.Apis.Auth" Version="1.73.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GregoryJenk.Mastermind.Service\GregoryJenk.Mastermind.Service.csproj" />
  </ItemGroup>
</Project>