name: Continuous Integration
on:
    push:
        branches:
            - "**"
        tags-ignore:
            - "**"
    pull_request:
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: 9.0.x
            - name: Restore
              run: dotnet restore src
            - name: Build
              run: dotnet build src --configuration Release --no-restore
            - name: Test
              run: dotnet test src --configuration Release --no-build
            - name: Coverage
              run: |
                dotnet tool install dotnet-coverage --global
                #dotnet test src --configuration Release --no-build --collect "Code Coverage"
                dotnet-coverage collect "dotnet test src --configuration Release --no-build" --output-format xml --output "dotnet-coverage.xml"